on:
  workflow_dispatch:
    inputs:
      project:
        description: "The project name. Specify the project relative to the root project."
        required: true
        type: choice
        options:
          - pto-scheduler
          - guess-the-word
          - kotlinx-serialization-ber
          - free-dsl

permissions: {}

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Setup repo
        uses: ./.github/actions/setup-env
        with:
          GRADLE_CONFIG_CACHE_KEY: ${{ secrets.GRADLE_CONFIG_CACHE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create release
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.MAVEN_CENTRAL_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.MAVEN_CENTRAL_TOKEN}}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{secrets.GPG_ARMORED_KEY}}
        run: ./gradlew :${{inputs.project}}:releaseCI --no-configuration-cache
